name: Deploy Website Python

on:
  push:
    branches:
      - main  # Menjalankan otomatisasi setiap ada push ke branch main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/actions-setup-python@v5
      with:
        python-version: '3.10'

    - name: Run Python Script
      run: python script.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages  # Hasil file index.html akan disimpan di branch ini
